name = "PDELib"
uuid = "89250b5f-5002-42e4-96e5-388c85c70594"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.1.1"

[deps]
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimplexGridFactory = "57bfcd06-606e-45d6-baf4-4ba06da0efd5"
VoronoiFVM = "82b139dc-5afc-11e9-35da-9b9bdfd336f3"

[compat]
ExtendableGrids = "^0.7.3"
ExtendableSparse = "^0.3.5"
GridVisualize = "^0.1.1"
Reexport = "1"
SimplexGridFactory = "^0.4.2"
VoronoiFVM = "^0.10.1"
julia = "^1.3"
